module.exports = /** @type {import('prettier').Config} */ ({
  trailingComma: 'all',
  arrowParens: 'always',
  singleQuote: true,
  printWidth: 100,
  importOrder: [
    '^types$',
    '^(react|react-dom)$',
    '^next(.*)$',
    '<THIRD_PARTY_MODULES>',
    '<BLANK_LINE>',
    '^services(/.*|$)',
    '^hooks(/.*|$)',
    '^queries(/.*|$)',
    '^(vectors|images)(/.*|$)',
    '^styles(/.*|$)',
    '^(pages|layouts|modules|common|components)(/.*|$)',
    '<BLANK_LINE>',
    '^[./]',
  ],
  plugins: [require('@trivago/prettier-plugin-sort-imports')],
});
